### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: Got HTTP/403 

### ISSUE THREAD

**Issue by LillySatou** [itskenny0/dumpia#17]
I have no idea what I did

PHP Fatal error:  Uncaught Exception: Got HTTP/403 - unable to fetch page. in Z:\dumpia\dumpia.php:188
Stack trace:
#0 Z:\dumpia\dumpia.php(209): Dumpia->fetch('https://fantia....')
#1 Z:\dumpia\dumpia.php(255): Dumpia->fetchJSON('https://fantia....', '1854290')
#2 Z:\dumpia\dumpia.php(147): Dumpia->getPostPhotos('1854290')
#3 Z:\dumpia\dumpia.php(344): Dumpia->main()
#4 {main}
  thrown in Z:\dumpia\dumpia.php on line 188

**Comment by LolLord-xT** [comment]
you did nothing wrong.
the Post API of fantia seems to check a CSRF token from the actual post page last time I checked, I very hastily added parsing that to my local copy, likely not pretty tho,

**Comment by LillySatou** [comment]
Ah okay. I tried a few others with some help from a friend and was getting the same error. Seems to be a common problem at the moment

**Comment by LolLord-xT** [comment]
you ppl can try this thing
https://gist.github.com/LolLord-xT/b46996b467c9867627e5f321617a1175
has been used in may so generally should work unless they changed something again.

if it dies with the message `captcha` you need to open a browser to fantia that uses the same session cookie and complete a captcha or fetch yourself a new session id.

also there are 2 new parameters.
`--newest postid` and `--oldest postid`, they both allow to set a bound on the oldest and newest post by post-id (inclusive)

has been only ever tested with downloading a single fanclub, so keep that in mind.
